######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 4 21:29:14 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += first_qt.cpp
